Add logging total lock time
coinbase/master_lock pull request #2
Opened 2017-06-15 18:56 UTC by jborrey

It is useful to know the total time that a lock was acquired for.

2017-06-30 19:02 UTC, jborrey commented
Alternative to using hashes in the logger would be to have 2 modes, one for strings and the other for hashes. But adding this complexity does not seem worth it.

2017-07-01 05:25 UTC, jimpo requested changes

2017-07-01 05:25 UTC, jimpo commented on lib/master_lock.rb
> +          key: key,
"key" will get censored by the log pipeline. Call it "lock_id" instead.

2017-07-01 05:25 UTC, jimpo commented on lib/master_lock.rb
> +      start_time = Time.now # used for benchmarking
What time is this? Do you want the amount of time the lock was held for or how long it took to acquire it?

2017-07-01 05:25 UTC, jimpo commented on README.md
> +  config.logger.level = Rails.env.test? ? :info : :debug
Remove the Rails reference. Makes it seem like this library depends on Rails.

2017-07-01 05:25 UTC, jimpo commented on README.md
> +  config.logger.formatter = proc do |_serverity, _time, _progname, msg|
Add explicit text above that the log formatter must accept hashes.

2017-07-01 05:25 UTC, jimpo commented on spec/spec_helper.rb
> -MasterLock.configure do |config|
Why remove this?

2017-07-01 16:57 UTC, jborrey commented on lib/master_lock.rb
> +      start_time = Time.now # used for benchmarking
amount of time the lock was held for.

2017-07-01 16:57 UTC, jborrey commented on lib/master_lock.rb
> +          key: key,
was working - but will do. i can see that happening elsewhere.

2017-07-01 16:57 UTC, jborrey commented on README.md
> +  config.logger.level = Rails.env.test? ? :info : :debug
yeah fair call.

2017-07-01 16:57 UTC, jborrey commented on README.md
> +  config.logger.formatter = proc do |_serverity, _time, _progname, msg|
okay

2017-07-01 16:58 UTC, jborrey commented on spec/spec_helper.rb
> -MasterLock.configure do |config|
oh my bad - was messing with tests too much. will put back

2017-08-02 16:53 UTC, jimpo commented on lib/master_lock.rb
> +      lock_acquired_start_time = Time.now # used for benchmarking
The lock has not been acquired yet. I don't think you are measuring the right thing.

2018-05-30 19:29 UTC, jimpo commented
Closing due to inactivity.

2018-05-30 19:29 UTC, closed without merging